# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(733, 440)
        self.Button_left = QtWidgets.QPushButton(Form)
        self.Button_left.setGeometry(QtCore.QRect(530, 250, 61, 61))
        self.Button_left.setObjectName("Button_left")
        self.Button_up = QtWidgets.QPushButton(Form)
        self.Button_up.setGeometry(QtCore.QRect(590, 190, 61, 61))
        self.Button_up.setObjectName("Button_up")
        self.Button_down = QtWidgets.QPushButton(Form)
        self.Button_down.setGeometry(QtCore.QRect(590, 310, 61, 61))
        self.Button_down.setObjectName("Button_down")
        self.Button_right = QtWidgets.QPushButton(Form)
        self.Button_right.setGeometry(QtCore.QRect(650, 250, 61, 61))
        self.Button_right.setObjectName("Button_right")
        self.open_camera = QtWidgets.QPushButton(Form)
        self.open_camera.setGeometry(QtCore.QRect(500, 30, 101, 61))
        self.open_camera.setObjectName("open_camera")
        self.close_camera = QtWidgets.QPushButton(Form)
        self.close_camera.setGeometry(QtCore.QRect(620, 30, 101, 61))
        self.close_camera.setObjectName("close_camera")
        self.video = QtWidgets.QLabel(Form)
        self.video.setGeometry(QtCore.QRect(20, 30, 461, 391))
        self.video.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video.setAutoFillBackground(True)
        self.video.setScaledContents(False)
        self.video.setAlignment(QtCore.Qt.AlignCenter)
        self.video.setWordWrap(False)
        self.video.setOpenExternalLinks(True)
        self.video.setObjectName("video")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 415, 731, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 0, 731, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(479, 10, 21, 421))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(-20, 10, 41, 421))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(720, 10, 21, 421))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.open_camera_2 = QtWidgets.QPushButton(Form)
        self.open_camera_2.setGeometry(QtCore.QRect(500, 110, 101, 61))
        self.open_camera_2.setObjectName("open_camera_2")
        self.open_camera_3 = QtWidgets.QPushButton(Form)
        self.open_camera_3.setGeometry(QtCore.QRect(620, 110, 101, 61))
        self.open_camera_3.setObjectName("open_camera_3")

        self.retranslateUi(Form)
        self.open_camera.clicked['bool'].connect(Form.camera_control_on) # type: ignore
        self.close_camera.clicked.connect(Form.camera_control_off) # type: ignore
        self.Button_left.clicked['bool'].connect(Form.left_move) # type: ignore
        self.Button_right.clicked['bool'].connect(Form.right_move) # type: ignore
        self.Button_up.clicked['bool'].connect(Form.up_move) # type: ignore
        self.Button_down.clicked['bool'].connect(Form.down_move) # type: ignore
        self.open_camera_2.clicked['bool'].connect(Form.screens_shot) # type: ignore
        self.open_camera_3.clicked['bool'].connect(Form.screen_detect) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Button_left.setText(_translate("Form", "左"))
        self.Button_up.setText(_translate("Form", "上"))
        self.Button_down.setText(_translate("Form", "下"))
        self.Button_right.setText(_translate("Form", "右"))
        self.open_camera.setText(_translate("Form", "打开摄像头"))
        self.close_camera.setText(_translate("Form", "关闭摄像头"))
        self.video.setText(_translate("Form", "VIDEO"))
        self.open_camera_2.setText(_translate("Form", "截图"))
        self.open_camera_3.setText(_translate("Form", "分析"))
